name: Mirror suprabot1

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror another repo
        run: |
          git fetch https://github.com/veerbot/suprabot1.git main
          git reset --hard FETCH_HEAD
          rm -rf .github/workflows

      - name: Force push mirror
        run: |
          git push origin main --force
