name: Extract Polyglot Books

on:
  workflow_dispatch:

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract zip into engines
        run: |
          unzip -o engines/polyglot-books.zip -d engines
